### PR TITLE
Converted DownloadActivity file to Kotlin

### PR DESCRIPTION
**Pull request by abkoradiya**

### CODE REVIEW

**Review by gouri-panda — APPROVED** [review]
Please format the code use `ctrl+shift+l`

**Comment by abkoradiya** [comment]
> Please format the code use `ctrl+shift+l`

In which file? I have already done in DownloadActivity,

**Comment by abkoradiya** [comment]
Hecktoberfest showing an "Ineligible Repository" label to this PR. Why?

**Comment by gouri-panda** [comment]
> Hecktoberfest showing an "Ineligible Repository" label to this PR. Why?

Done. Could you see if it works now?

**Comment by abkoradiya** [comment]
> > Hecktoberfest showing an "Ineligible Repository" label to this PR. Why?
> 
> Done. Could you see if it works now?

ok now work. Can you tell me how you have solved it?

**Pull request merged**
